// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMJrw8uYRhuFOI-OKIRi2h4uozArJPpE',
    appId: '1:814541279545:web:b4908cfcb42a4cd3d5d8e8',
    messagingSenderId: '814541279545',
    projectId: 'annisa-flutter',
    authDomain: 'annisa-flutter.firebaseapp.com',
    storageBucket: 'annisa-flutter.appspot.com',
    measurementId: 'G-F4001M4DST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNaSESmBQlTpGZGYRqnpghaZVTiiKv9U',
    appId: '1:814541279545:android:93c26bd4a22ddb93d5d8e8',
    messagingSenderId: '814541279545',
    projectId: 'annisa-flutter',
    storageBucket: 'annisa-flutter.appspot.com',
  );
}
